//#ENJOY
/**

░▒▓█▓▒░░▒▓█▓▒░░▒▓█▓▒░░▒▓██████▓▒░ ░▒▓███████▓▒░▒▓█▓▒░ 
░▒▓█▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░ 
░▒▓█▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░ 
░▒▓█▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓████████▓▒░░▒▓██████▓▒░░▒▓█▓▒░ 
░▒▓█▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░▒▓█▓▒░ 
░▒▓█▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░▒▓█▓▒░ 
 ░▒▓█████████████▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓███████▓▒░░▒▓█▓▒░ 
                                                      

**/

const fs = require("fs-extra");
if (fs.existsSync(".env"))
  require("dotenv").config({ path: __dirname + "/.env" });
global.audio = "";
global.video = "";
global.port = process.env.PORT;
global.appUrl = process.env.APP_URL || "";
global.email = "wasixml@gmail.com";
global.location = "Lahore,Pakistan.";
global.mongodb = process.env.MONGODB_URI || "";
global.allowJids = process.env.ALLOW_JID || "923192173398@s.whatsapp.net";
global.blockJids = process.env.BLOCK_JID || "null";
global.DATABASE_URL = process.env.DATABASE_URL || "";
global.timezone = process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github = process.env.GITHUB || "https://github.com/Itxxwasi/WASI-MD-V2";
global.gurl = process.env.GURL || "https://whatsapp.com/channel/0029VaDK8ZUDjiOhwFS1cP2j";
global.website = process.env.GURL || "https://whatsapp.com/channel/0029VaDK8ZUDjiOhwFS1cP2j";
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/1f4e6e1cc2ed1662adb36.jpg";
global.devs = "923135673658";
global.sudo = process.env.SUDO || "923192173398";
global.owner = process.env.OWNER_NUMBER || "923192173398";
global.style = process.env.STYLE || "3";
global.gdbye = process.env.GOODBYE || "false";
global.wlcm = process.env.WELCOME || "false";
global.warncount = process.env.WARN_COUNT || 3;
global.disablepm = process.env.DISABLE_PM || "false";
global.disablegroup = process.env.DISABLE_GROUPS || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG || "true";
global.userImages = process.env.USER_IMAGES || "";
global.waPresence = process.env.WAPRESENCE || "recording";
global.readcmds = process.env.READ_COMMAND || "false";
global.readmessage = process.env.READ_MESSAGE || "false";
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "";
global.read_status = process.env.AUTO_READ_STATUS || "true";
global.save_status = process.env.AUTO_SAVE_STATUS || "false";
global.save_status_from = process.env.SAVE_STATUS_FROM || "";
global.read_status_from = process.env.READ_STATUS_FROM || "";
global.autoreaction = process.env.autoreaction || "true";

global.api_smd = "https://api-smd-1.vercel.app";
global.scan = "https://pair-qr-wasi-md.onrender.com";

global.SESSION_ID =
  process.env.SESSION_ID ||
  "SUHAIL_19_57_07_01_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgOCxcbiAgICAgICAgMTQ2LFxuICAgICAgICAyMixcbiAgICAgICAgMTI4LFxuICAgICAgICAxNDUsXG4gICAgICAgIDk0LFxuICAgICAgICAzOSxcbiAgICAgICAgODgsXG4gICAgICAgIDEyNSxcbiAgICAgICAgMzMsXG4gICAgICAgIDI0OSxcbiAgICAgICAgMjU0LFxuICAgICAgICA5MCxcbiAgICAgICAgMzYsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMTI1LFxuICAgICAgICAxNzAsXG4gICAgICAgIDk0LFxuICAgICAgICAyOCxcbiAgICAgICAgMTEwLFxuICAgICAgICAyNTAsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMjQwLFxuICAgICAgICA2MixcbiAgICAgICAgOSxcbiAgICAgICAgMTgsXG4gICAgICAgIDIzNixcbiAgICAgICAgMjUyLFxuICAgICAgICA5MCxcbiAgICAgICAgNTIsXG4gICAgICAgIDIyLFxuICAgICAgICA4N1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMzAsXG4gICAgICAgIDIzNixcbiAgICAgICAgMTczLFxuICAgICAgICAxNyxcbiAgICAgICAgMTE0LFxuICAgICAgICAxMjksXG4gICAgICAgIDE5NixcbiAgICAgICAgMTYyLFxuICAgICAgICAxMzcsXG4gICAgICAgIDEzMCxcbiAgICAgICAgNzgsXG4gICAgICAgIDE2NixcbiAgICAgICAgMTYwLFxuICAgICAgICAyNDYsXG4gICAgICAgIDU3LFxuICAgICAgICAyMTYsXG4gICAgICAgIDEwOCxcbiAgICAgICAgMTE3LFxuICAgICAgICAxOTUsXG4gICAgICAgIDExOCxcbiAgICAgICAgMTg1LFxuICAgICAgICA0NSxcbiAgICAgICAgMjA5LFxuICAgICAgICAxMTcsXG4gICAgICAgIDk3LFxuICAgICAgICAxOTIsXG4gICAgICAgIDY2LFxuICAgICAgICAxOTQsXG4gICAgICAgIDIxOCxcbiAgICAgICAgNDIsXG4gICAgICAgIDEzNCxcbiAgICAgICAgNTRcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDgsXG4gICAgICAgIDg5LFxuICAgICAgICAyMTIsXG4gICAgICAgIDQ0LFxuICAgICAgICAyMCxcbiAgICAgICAgMTE1LFxuICAgICAgICAxOCxcbiAgICAgICAgMTYsXG4gICAgICAgIDEwNixcbiAgICAgICAgMTI5LFxuICAgICAgICAyNCxcbiAgICAgICAgMTAxLFxuICAgICAgICA2NyxcbiAgICAgICAgMTA3LFxuICAgICAgICA4NSxcbiAgICAgICAgMjEsXG4gICAgICAgIDQxLFxuICAgICAgICAyMzcsXG4gICAgICAgIDE5OSxcbiAgICAgICAgMTAzLFxuICAgICAgICAyNDIsXG4gICAgICAgIDQxLFxuICAgICAgICA1MSxcbiAgICAgICAgMjEzLFxuICAgICAgICAyMTIsXG4gICAgICAgIDE2OSxcbiAgICAgICAgNjIsXG4gICAgICAgIDI3LFxuICAgICAgICAxMyxcbiAgICAgICAgNzYsXG4gICAgICAgIDIzNyxcbiAgICAgICAgMTI1XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDg4LFxuICAgICAgICA5OCxcbiAgICAgICAgMjIxLFxuICAgICAgICA1NSxcbiAgICAgICAgNDMsXG4gICAgICAgIDMxLFxuICAgICAgICAxNjcsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMTI2LFxuICAgICAgICA5OSxcbiAgICAgICAgMjQ2LFxuICAgICAgICAxMjcsXG4gICAgICAgIDk0LFxuICAgICAgICA2LFxuICAgICAgICAxODgsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMCxcbiAgICAgICAgMTE4LFxuICAgICAgICAxMjQsXG4gICAgICAgIDExNSxcbiAgICAgICAgMTM1LFxuICAgICAgICA4NyxcbiAgICAgICAgMjAwLFxuICAgICAgICAyMDksXG4gICAgICAgIDEzNixcbiAgICAgICAgMjMwLFxuICAgICAgICA4NCxcbiAgICAgICAgMTIyLFxuICAgICAgICAxMDMsXG4gICAgICAgIDg2LFxuICAgICAgICAyMDAsXG4gICAgICAgIDI1XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMjAsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMjQwLFxuICAgICAgICAxODgsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMTE1LFxuICAgICAgICAxNjksXG4gICAgICAgIDUxLFxuICAgICAgICAyNTIsXG4gICAgICAgIDk3LFxuICAgICAgICAxNTQsXG4gICAgICAgIDIyNixcbiAgICAgICAgOTcsXG4gICAgICAgIDE1MyxcbiAgICAgICAgMTAyLFxuICAgICAgICAxMTUsXG4gICAgICAgIDg2LFxuICAgICAgICAxOTAsXG4gICAgICAgIDg1LFxuICAgICAgICAxMzksXG4gICAgICAgIDE1OCxcbiAgICAgICAgMTE3LFxuICAgICAgICAxNixcbiAgICAgICAgMTc2LFxuICAgICAgICAyMjcsXG4gICAgICAgIDcsXG4gICAgICAgIDk2LFxuICAgICAgICAyOSxcbiAgICAgICAgNDAsXG4gICAgICAgIDIwNyxcbiAgICAgICAgNDksXG4gICAgICAgIDEyN1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMDEsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMTg3LFxuICAgICAgICAxOTcsXG4gICAgICAgIDg2LFxuICAgICAgICA0NyxcbiAgICAgICAgMjE4LFxuICAgICAgICAxODQsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMjUyLFxuICAgICAgICAyMjMsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMTYxLFxuICAgICAgICAyNSxcbiAgICAgICAgOTAsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMjI1LFxuICAgICAgICA1OSxcbiAgICAgICAgMTEyLFxuICAgICAgICAyMDUsXG4gICAgICAgIDE1OSxcbiAgICAgICAgMjE1LFxuICAgICAgICAxNSxcbiAgICAgICAgMjgsXG4gICAgICAgIDIwOCxcbiAgICAgICAgNzYsXG4gICAgICAgIDIxOCxcbiAgICAgICAgMTIsXG4gICAgICAgIDE1LFxuICAgICAgICAxMDAsXG4gICAgICAgIDE5NyxcbiAgICAgICAgNzdcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgOTYsXG4gICAgICAgICAgMTM1LFxuICAgICAgICAgIDQyLFxuICAgICAgICAgIDE4LFxuICAgICAgICAgIDEzMixcbiAgICAgICAgICAxMTUsXG4gICAgICAgICAgMTMzLFxuICAgICAgICAgIDEwMSxcbiAgICAgICAgICAxMzYsXG4gICAgICAgICAgMjUsXG4gICAgICAgICAgODYsXG4gICAgICAgICAgOSxcbiAgICAgICAgICAyMyxcbiAgICAgICAgICAyNTEsXG4gICAgICAgICAgNTUsXG4gICAgICAgICAgMjQ2LFxuICAgICAgICAgIDIyMixcbiAgICAgICAgICAxNDMsXG4gICAgICAgICAgMTU4LFxuICAgICAgICAgIDEyNyxcbiAgICAgICAgICA4NyxcbiAgICAgICAgICAyLFxuICAgICAgICAgIDYzLFxuICAgICAgICAgIDEwNCxcbiAgICAgICAgICAyNDgsXG4gICAgICAgICAgMTA4LFxuICAgICAgICAgIDUyLFxuICAgICAgICAgIDEwMyxcbiAgICAgICAgICAxNCxcbiAgICAgICAgICAzMyxcbiAgICAgICAgICA1NyxcbiAgICAgICAgICA5N1xuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAyNDEsXG4gICAgICAgICAgMTI5LFxuICAgICAgICAgIDE3NCxcbiAgICAgICAgICA1NSxcbiAgICAgICAgICA2LFxuICAgICAgICAgIDE4NCxcbiAgICAgICAgICAxOTYsXG4gICAgICAgICAgMjE5LFxuICAgICAgICAgIDk3LFxuICAgICAgICAgIDEwNixcbiAgICAgICAgICAxMDYsXG4gICAgICAgICAgOTEsXG4gICAgICAgICAgNjAsXG4gICAgICAgICAgMjcsXG4gICAgICAgICAgMjEsXG4gICAgICAgICAgMTcwLFxuICAgICAgICAgIDE5MixcbiAgICAgICAgICA4MixcbiAgICAgICAgICA3NixcbiAgICAgICAgICAyMDgsXG4gICAgICAgICAgMTIzLFxuICAgICAgICAgIDIwMCxcbiAgICAgICAgICAzNSxcbiAgICAgICAgICAxNzYsXG4gICAgICAgICAgMjQwLFxuICAgICAgICAgIDEzNixcbiAgICAgICAgICAyMTksXG4gICAgICAgICAgMTc3LFxuICAgICAgICAgIDMxLFxuICAgICAgICAgIDEzNCxcbiAgICAgICAgICA2MSxcbiAgICAgICAgICA4MFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDYxLFxuICAgICAgICA5MixcbiAgICAgICAgNzgsXG4gICAgICAgIDEzNyxcbiAgICAgICAgMTk5LFxuICAgICAgICA5LFxuICAgICAgICA1OSxcbiAgICAgICAgMjAsXG4gICAgICAgIDE2NSxcbiAgICAgICAgMTE3LFxuICAgICAgICAyNDUsXG4gICAgICAgIDEzMSxcbiAgICAgICAgMTI5LFxuICAgICAgICAxMTcsXG4gICAgICAgIDIzMSxcbiAgICAgICAgOTksXG4gICAgICAgIDg3LFxuICAgICAgICAxNjMsXG4gICAgICAgIDc5LFxuICAgICAgICA2OSxcbiAgICAgICAgNjksXG4gICAgICAgIDI1MixcbiAgICAgICAgNDcsXG4gICAgICAgIDI1MSxcbiAgICAgICAgOTIsXG4gICAgICAgIDIwMyxcbiAgICAgICAgMTYxLFxuICAgICAgICAxMDksXG4gICAgICAgIDE4MSxcbiAgICAgICAgMzUsXG4gICAgICAgIDQyLFxuICAgICAgICA0MyxcbiAgICAgICAgNTEsXG4gICAgICAgIDIwNSxcbiAgICAgICAgMjA2LFxuICAgICAgICAyMTAsXG4gICAgICAgIDQzLFxuICAgICAgICAyMCxcbiAgICAgICAgMTg2LFxuICAgICAgICAyMTEsXG4gICAgICAgIDE4MixcbiAgICAgICAgMjQ3LFxuICAgICAgICAyMTEsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMTk0LFxuICAgICAgICAxNDAsXG4gICAgICAgIDIxLFxuICAgICAgICAyNTMsXG4gICAgICAgIDYxLFxuICAgICAgICAyMjEsXG4gICAgICAgIDk0LFxuICAgICAgICA2LFxuICAgICAgICA0MixcbiAgICAgICAgMjgsXG4gICAgICAgIDU2LFxuICAgICAgICAzOCxcbiAgICAgICAgMTU3LFxuICAgICAgICAxMDEsXG4gICAgICAgIDksXG4gICAgICAgIDIxNixcbiAgICAgICAgMTgxLFxuICAgICAgICAxNjksXG4gICAgICAgIDEzMCxcbiAgICAgICAgMTM5XG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiA4MixcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJIb1R6ejZDT1lBTHhZL1RvSUY4dDZLUWQwVStCaVpGTU1VdllmVWtlSGNVPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDAsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJUQ05yZEJra1I3U1IyMm52cmdVTFRBXCIsXG4gIFwicGhvbmVJZFwiOiBcIjIyZTNjZTRjLWJhMWMtNDczZS05ZjkzLTE4ZGFjMzQzODZjM1wiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAyMjUsXG4gICAgICA2NSxcbiAgICAgIDE3NSxcbiAgICAgIDIyMixcbiAgICAgIDE4LFxuICAgICAgMTcwLFxuICAgICAgNTksXG4gICAgICAyMSxcbiAgICAgIDg3LFxuICAgICAgMTc2LFxuICAgICAgMTQ0LFxuICAgICAgMTEzLFxuICAgICAgMjEwLFxuICAgICAgMTMzLFxuICAgICAgMjAwLFxuICAgICAgNzUsXG4gICAgICAxMixcbiAgICAgIDE4MCxcbiAgICAgIDE3MSxcbiAgICAgIDI2XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogdHJ1ZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDMxLFxuICAgICAgMTM5LFxuICAgICAgODMsXG4gICAgICAzNyxcbiAgICAgIDMzLFxuICAgICAgMjI0LFxuICAgICAgMjI5LFxuICAgICAgNDMsXG4gICAgICAyMTksXG4gICAgICAxMyxcbiAgICAgIDU1LFxuICAgICAgMTEwLFxuICAgICAgOTQsXG4gICAgICAxNDAsXG4gICAgICA2NixcbiAgICAgIDIxMyxcbiAgICAgIDE4MyxcbiAgICAgIDEyLFxuICAgICAgMTgwLFxuICAgICAgMTU0XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIjI4NzdCTDdLXCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCIyNjM3MTE0ODc0NjU6MTlAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjI3MDIwMTEyMzgwNzQ0OToxOUBsaWRcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNMN0hudWtHRUtPVWpMUUdHQVVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcInU0RitsK0thanJETTFxLzc3NHU1Mi9IVWRNRml1V2NuUjBMTWJGNTVMbE09XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwib1hrY29yTGZLeXQ0cUJRR3A5YUN2QXoreFNsLy9uaVVPNGtpazZ5Smk0MlA1TnE4bmxMNk1mcXo4OFFPMkhpSU5YWW52RFlHendiN2VOcFdVUU5LQ1E9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiVUcySXh3UlRHcnBSd2ZURXkvSkNHZ0lFZUt4RmJIaVMxTEdwN3hJSGJDdjltd2ZKejJqdm5NUVhXTlhnU0ErdG96UnhDVVU2cEEwUnllSy9EWE9OZ0E9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjYzNzExNDg3NDY1OjE5QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMTg3LFxuICAgICAgICAgIDEyOSxcbiAgICAgICAgICAxMjYsXG4gICAgICAgICAgMTUxLFxuICAgICAgICAgIDIyNixcbiAgICAgICAgICAxNTQsXG4gICAgICAgICAgMTQyLFxuICAgICAgICAgIDE3NixcbiAgICAgICAgICAyMDQsXG4gICAgICAgICAgMjE0LFxuICAgICAgICAgIDE3NSxcbiAgICAgICAgICAyNTEsXG4gICAgICAgICAgMjM5LFxuICAgICAgICAgIDEzOSxcbiAgICAgICAgICAxODUsXG4gICAgICAgICAgMjE5LFxuICAgICAgICAgIDI0MSxcbiAgICAgICAgICAyMTIsXG4gICAgICAgICAgMTE2LFxuICAgICAgICAgIDE5MyxcbiAgICAgICAgICA5OCxcbiAgICAgICAgICAxODUsXG4gICAgICAgICAgMTAzLFxuICAgICAgICAgIDM5LFxuICAgICAgICAgIDcxLFxuICAgICAgICAgIDY2LFxuICAgICAgICAgIDIwNCxcbiAgICAgICAgICAxMDgsXG4gICAgICAgICAgOTQsXG4gICAgICAgICAgMTIxLFxuICAgICAgICAgIDQ2LFxuICAgICAgICAgIDgzXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJhbmRyb2lkXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MTk4NjM4NDYsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFEN2VcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUQ3ZS5qc29uIjogIntcImtleURhdGFcIjpcInRmL0tTd1N3UDY5ckt3Um1XaVltQXRkRDE4NCtvNDN3b3BxMXFYQ1RIR0E9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTgzMTMxNDM2NixcImN1cnJlbnRJbmRleFwiOjMsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzE3NDU0NjcyOTk1XCJ9Igp9"
module.exports = {
  menu: process.env.MENU || "",
  HANDLERS: process.env.PREFIX || ".",
  BRANCH: process.env.BRANCH || "main",
  VERSION: process.env.VERSION || "1.0.0",
  caption: process.env.CAPTION || "𝐅𝐈𝐋𝐄-𝐆𝐄𝐍𝐄𝐑𝐀𝐓𝐄𝐃-𝐁𝐘-𝐖𝐀𝐒𝐈-𝐌𝐃-𝐕2😍",
  author: process.env.PACK_AUTHER || "WASO",
  packname: process.env.PACK_NAME || "♥️",
  botname: process.env.BOT_NAME || "𝐖𝐀𝐒𝐈-𝐌𝐃-𝐕2",
  ownername: process.env.OWNER_NAME || "WASI",
  errorChat: process.env.ERROR_CHAT || "923192173398",
  KOYEB_API: process.env.KOYEB_API || "false",
  REMOVE_BG_KEY: process.env.REMOVE_BG_KEY || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME: process.env.HEROKU_APP_NAME || "",
  antilink_values: process.env.ANTILINK_VALUES || "chat.whatsapp.com",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,
  aitts_Voice_Id: process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE || process.env.MODE || "private",
  AUTOREACTION: process.env.AUTOREACTION || process.env.AUTOREACTION || "true",
  LANG: (process.env.THEME || "WASI").toUpperCase(),
};
global.rank = "updated";
global.isMongodb = false;
let file = require.resolve(__filename);
fs.watchFile(file, () => {
  fs.unwatchFile(file);
  console.log(`Update'${__filename}'`);
  delete require.cache[file];
  require(file);
});
